export const PRIME_ICONS_LIST = [
    { label: 'Align Center', value: 'pi-align-center' },
    { label: 'Align Justify', value: 'pi-align-justify' },
    { label: 'Align Left', value: 'pi-align-left' },
    { label: 'Align Right', value: 'pi-align-right' },
    { label: 'Amazon', value: 'pi-amazon' },
    { label: 'Android', value: 'pi-android' },
    { label: 'Apple', value: 'pi-apple' },
    { label: 'Bars', value: 'pi-bars' },
    { label: 'Bell', value: 'pi-bell' },
    { label: 'Bitcoin', value: 'pi-bitcoin' },
    { label: 'Bolt', value: 'pi-bolt' },
    { label: 'Book', value: 'pi-book' },
    { label: 'Bookmark', value: 'pi-bookmark' },
    { label: 'Box', value: 'pi-box' },
    { label: 'Briefcase', value: 'pi-briefcase' },
    { label: 'Building', value: 'pi-building' },
    { label: 'Calculator', value: 'pi-calculator' },
    { label: 'Calendar', value: 'pi-calendar' },
    { label: 'Camera', value: 'pi-camera' },
    { label: 'Car', value: 'pi-car' },
    { label: 'Cart Plus', value: 'pi-cart-plus' },
    { label: 'Chart Bar', value: 'pi-chart-bar' },
    { label: 'Chart Line', value: 'pi-chart-line' },
    { label: 'Chart Pie', value: 'pi-chart-pie' },
    { label: 'Check', value: 'pi-check' },
    { label: 'Check Circle', value: 'pi-check-circle' },
    { label: 'Clock', value: 'pi-clock' },
    { label: 'Clone', value: 'pi-clone' },
    { label: 'Cloud', value: 'pi-cloud' },
    { label: 'Cloud Download', value: 'pi-cloud-download' },
    { label: 'Cloud Upload', value: 'pi-cloud-upload' },
    { label: 'Code', value: 'pi-code' },
    { label: 'Cog', value: 'pi-cog' },
    { label: 'Comments', value: 'pi-comments' },
    { label: 'Compass', value: 'pi-compass' },
    { label: 'Copy', value: 'pi-copy' },
    { label: 'Credit Card', value: 'pi-credit-card' },
    { label: 'Database', value: 'pi-database' },
    { label: 'Desktop', value: 'pi-desktop' },
    { label: 'Discord', value: 'pi-discord' },
    { label: 'Download', value: 'pi-download' },
    { label: 'Envelope', value: 'pi-envelope' },
    { label: 'Euro', value: 'pi-euro' },
    { label: 'Exclamation Circle', value: 'pi-exclamation-circle' },
    { label: 'Exclamation Triangle', value: 'pi-exclamation-triangle' },
    { label: 'External Link', value: 'pi-external-link' },
    { label: 'Eye', value: 'pi-eye' },
    { label: 'Eye Slash', value: 'pi-eye-slash' },
    { label: 'Facebook', value: 'pi-facebook' },
    { label: 'File', value: 'pi-file' },
    { label: 'File Excel', value: 'pi-file-excel' },
    { label: 'File Pdf', value: 'pi-file-pdf' },
    { label: 'Filter', value: 'pi-filter' },
    { label: 'Flag', value: 'pi-flag' },
    { label: 'Folder', value: 'pi-folder' },
    { label: 'Folder Open', value: 'pi-folder-open' },
    { label: 'Github', value: 'pi-github' },
    { label: 'Globe', value: 'pi-globe' },
    { label: 'Google', value: 'pi-google' },
    { label: 'Hashtag', value: 'pi-hashtag' },
    { label: 'Heart', value: 'pi-heart' },
    { label: 'History', value: 'pi-history' },
    { label: 'Home', value: 'pi-home' },
    { label: 'Id Card', value: 'pi-id-card' },
    { label: 'Image', value: 'pi-image' },
    { label: 'Images', value: 'pi-images' },
    { label: 'Inbox', value: 'pi-inbox' },
    { label: 'Info Circle', value: 'pi-info-circle' },
    { label: 'Instagram', value: 'pi-instagram' },
    { label: 'Key', value: 'pi-key' },
    { label: 'Language', value: 'pi-language' },
    { label: 'Link', value: 'pi-link' },
    { label: 'Linkedin', value: 'pi-linkedin' },
    { label: 'List', value: 'pi-list' },
    { label: 'Lock', value: 'pi-lock' },
    { label: 'Lock Open', value: 'pi-lock-open' },
    { label: 'Map', value: 'pi-map' },
    { label: 'Map Marker', value: 'pi-map-marker' },
    { label: 'Megaphone', value: 'pi-megaphone' },
    { label: 'Microphone', value: 'pi-microphone' },
    { label: 'Minus', value: 'pi-minus' },
    { label: 'Mobile', value: 'pi-mobile' },
    { label: 'Money Bill', value: 'pi-money-bill' },
    { label: 'Moon', value: 'pi-moon' },
    { label: 'Palette', value: 'pi-palette' },
    { label: 'Paperclip', value: 'pi-paperclip' },
    { label: 'Pause', value: 'pi-pause' },
    { label: 'Paypal', value: 'pi-paypal' },
    { label: 'Pencil', value: 'pi-pencil' },
    { label: 'Percentage', value: 'pi-percentage' },
    { label: 'Phone', value: 'pi-phone' },
    { label: 'Play', value: 'pi-play' },
    { label: 'Plus', value: 'pi-plus' },
    { label: 'Pound', value: 'pi-pound' },
    { label: 'Power Off', value: 'pi-power-off' },
    { label: 'Print', value: 'pi-print' },
    { label: 'Qrcode', value: 'pi-qrcode' },
    { label: 'Question Circle', value: 'pi-question-circle' },
    { label: 'Reddit', value: 'pi-reddit' },
    { label: 'Refresh', value: 'pi-refresh' },
    { label: 'Reply', value: 'pi-reply' },
    { label: 'Save', value: 'pi-save' },
    { label: 'Search', value: 'pi-search' },
    { label: 'Search Minus', value: 'pi-search-minus' },
    { label: 'Search Plus', value: 'pi-search-plus' },
    { label: 'Send', value: 'pi-send' },
    { label: 'Server', value: 'pi-server' },
    { label: 'Share Alt', value: 'pi-share-alt' },
    { label: 'Shield', value: 'pi-shield' },
    { label: 'Shopping Bag', value: 'pi-shopping-bag' },
    { label: 'Shopping Cart', value: 'pi-shopping-cart' },
    { label: 'Sign In', value: 'pi-sign-in' },
    { label: 'Sign Out', value: 'pi-sign-out' },
    { label: 'Sitemap', value: 'pi-sitemap' },
    { label: 'Slack', value: 'pi-slack' },
    { label: 'Sliders H', value: 'pi-sliders-h' },
    { label: 'Sliders V', value: 'pi-sliders-v' },
    { label: 'Spinner', value: 'pi-spinner' },
    { label: 'Star', value: 'pi-star' },
    { label: 'Stop', value: 'pi-stop' },
    { label: 'Sun', value: 'pi-sun' },
    { label: 'Sync', value: 'pi-sync' },
    { label: 'Table', value: 'pi-table' },
    { label: 'Tablet', value: 'pi-tablet' },
    { label: 'Tag', value: 'pi-tag' },
    { label: 'Tags', value: 'pi-tags' },
    { label: 'Telegram', value: 'pi-telegram' },
    { label: 'Th Large', value: 'pi-th-large' },
    { label: 'Thumbs Down', value: 'pi-thumbs-down' },
    { label: 'Thumbs Up', value: 'pi-thumbs-up' },
    { label: 'Ticket', value: 'pi-ticket' },
    { label: 'Tiktok', value: 'pi-tiktok' },
    { label: 'Times', value: 'pi-times' },
    { label: 'Trash', value: 'pi-trash' },
    { label: 'Trophy', value: 'pi-trophy' },
    { label: 'Truck', value: 'pi-truck' },
    { label: 'Twitch', value: 'pi-twitch' },
    { label: 'Twitter', value: 'pi-twitter' },
    { label: 'Undo', value: 'pi-undo' },
    { label: 'Unlock', value: 'pi-unlock' },
    { label: 'Upload', value: 'pi-upload' },
    { label: 'User', value: 'pi-user' },
    { label: 'User Edit', value: 'pi-user-edit' },
    { label: 'User Minus', value: 'pi-user-minus' },
    { label: 'User Plus', value: 'pi-user-plus' },
    { label: 'Users', value: 'pi-users' },
    { label: 'Video', value: 'pi-video' },
    { label: 'Vimeo', value: 'pi-vimeo' },
    { label: 'Volume Down', value: 'pi-volume-down' },
    { label: 'Volume Off', value: 'pi-volume-off' },
    { label: 'Volume Up', value: 'pi-volume-up' },
    { label: 'Wallet', value: 'pi-wallet' },
    { label: 'Whatsapp', value: 'pi-whatsapp' },
    { label: 'Wifi', value: 'pi-wifi' },
    { label: 'Wrench', value: 'pi-wrench' },
    { label: 'Youtube', value: 'pi-youtube' }
];
